/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getWindowsInfo(): WindowsInfo

/** Windows 通知选项 */
export interface NotificationOptions {
  title: string
  message: string
}

/** Windows 通知结果 */
export interface NotificationResult {
  success: boolean
  message: string
}

/** 发送 Windows 系统通知 */
export declare function sendNotification(options: NotificationOptions): NotificationResult

export interface WindowsInfo {
  osVersion: string
  systemDir: string
  processCount?: number
  ipAddresses: Array<string>
}
